removed v0.6.0 package
removed v0.6.0 package


Because of (https://chat.fhir.org/#narrow/stream/328836-tooling.2FPackage-Crawlers/topic/stream.20events/near/432689847):

Processing meta feed entry: University Medicine Greifswald - Department of Anesthesia, Intensive Care, Emergency and Pain Medicine
Processing: https://github.com/umg-minai/fhir-package-feed/blob/main/package-feed.xml?raw=true

Downloading package: de.netzwerk-universitaetsmedizin.ebm-cpg version: 0.6.0
Error: The name of the package 'ebm-cpg.netzwerk-universitaetsmedizin.de' does not match the name in the feed 'de.netzwerk-universitaetsmedizin.ebm-cpg'
Feed University Medicine Greifswald - Department of Anesthesia, Intensive Care, Emergency and Pain Medicine processed.